"""Milestone repository port."""

from typing import Protocol

from portfolio_manager.domain.models import Milestone


class MilestoneRepository(Protocol):
    """Persistence contract for :class:`Milestone`.

    ``list_for_project`` orders by ``sort_order`` then ``id`` (deterministic).
    ``count`` returns ``(total, done)`` counts excluding cancelled milestones,
    which the SRS excludes from scoring.
    """

    def create(self, milestone: Milestone) -> Milestone: ...
    def get(self, milestone_id: int) -> Milestone: ...
    def list_for_project(self, project_id: int) -> list[Milestone]: ...
    def list_for_project_with_totals(self, project_id: int) -> list[tuple[Milestone, int]]: ...
    def update(self, milestone: Milestone) -> Milestone: ...
    def delete(self, milestone_id: int) -> None: ...
    def count(self, project_id: int) -> tuple[int, int]: ...
