"""Sidecar authentication token handling.

The token is generated by the Rust supervisor once per launch and passed to the
sidecar via the ``PORTFOLIO_SIDECAR_TOKEN`` environment variable or stdin — never
as a command-line argument, to keep it out of the process list. Comparison is
timing-safe.
"""

import hmac
import os
import sys

#: Environment variable the Rust supervisor uses to pass the token.
TOKEN_ENV_VAR = "PORTFOLIO_SIDECAR_TOKEN"


def read_startup_token() -> str:
    """Read the auth token from the environment, falling back to stdin.

    :returns: The token string (may be empty if none supplied).
    :rtype: str
    """
    token = os.environ.get(TOKEN_ENV_VAR, "")
    if token:
        return token
    # Fallback: a single line on stdin (non-blocking best-effort).
    if not sys.stdin.isatty():
        try:
            line = sys.stdin.readline()
            return line.strip()
        except Exception:  # noqa: BLE001
            return ""
    return ""


def tokens_match(expected: str, provided: str | None) -> bool:
    """Return ``True`` if *provided* matches *expected* using a timing-safe compare.

    :param expected: The server's configured token.
    :param provided: The token supplied by the caller (may be ``None``).
    :rtype: bool
    """
    if not expected or not provided:
        return False
    return hmac.compare_digest(expected, provided)
