#!/usr/bin/env python3
"""Emit a deterministic OpenAPI document and generate TypeScript contract types.

Builds the FastAPI app (development mode, in-memory DB, no token) purely to
extract its OpenAPI schema — the app is never served. Writes:

- ``frontend/src/contracts/generated/openapi.json``
- ``frontend/src/contracts/generated/types.ts`` (a hand-rolled, dependency-free
  emitter covering the component schemas used by the renderer)

Run in CI and fail when committed output differs from freshly generated output
(contract-drift gate). For richer generation, swap the emitter for
``openapi-typescript``; the drift check is what matters.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_SRC = REPO_ROOT / "backend" / "src"
OUT_DIR = REPO_ROOT / "frontend" / "src" / "contracts" / "generated"

sys.path.insert(0, str(BACKEND_SRC))


def build_openapi() -> dict:
    """Return the OpenAPI schema for the app.

    :rtype: dict
    """
    from portfolio_manager.api.app import create_app
    from portfolio_manager.bootstrap import build_container

    container = build_container(db_path=":memory:", token="", production=False)
    app = create_app(container)
    schema = app.openapi()
    container.close()
    return schema


_TS_TYPES = {
    "integer": "number",
    "number": "number",
    "string": "string",
    "boolean": "boolean",
}


def _ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(_ts_type(s) for s in schema["anyOf"])
    t = schema.get("type")
    if t == "array":
        return f"{_ts_type(schema.get('items', {}))}[]"
    if t == "null":
        return "null"
    if isinstance(t, str) and t in _TS_TYPES:
        return _TS_TYPES[t]
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    return "unknown"


def emit_types(schema: dict) -> str:
    """Emit TypeScript interfaces for all component schemas.

    :param schema: The OpenAPI document.
    :rtype: str
    """
    lines = [
        "// AUTO-GENERATED by scripts/generate_openapi.py — do not edit by hand.",
        "// Regenerate with: python scripts/generate_openapi.py",
        "",
    ]
    components = schema.get("components", {}).get("schemas", {})
    for name in sorted(components):
        model = components[name]
        if "enum" in model and model.get("type") == "string":
            values = " | ".join(json.dumps(v) for v in model["enum"])
            lines.append(f"export type {name} = {values};")
            lines.append("")
            continue
        props = model.get("properties", {})
        required = set(model.get("required", []))
        lines.append(f"export interface {name} {{")
        for prop, pschema in props.items():
            optional = "" if prop in required else "?"
            lines.append(f"  {prop}{optional}: {_ts_type(pschema)};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Generate the OpenAPI JSON and TypeScript types.

    :returns: Process exit code.
    :rtype: int
    """
    schema = build_openapi()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "openapi.json").write_text(
        json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (OUT_DIR / "types.ts").write_text(emit_types(schema), encoding="utf-8")
    print(f"Wrote {OUT_DIR / 'openapi.json'} and {OUT_DIR / 'types.ts'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
